togglBaseURL: 'https://api.track.toggl.com/api/v9'
togglAPIToken: ''

# Get your account ID by using the Atlassian/JIRA API: https://your-domain.atlassian.com/rest/api/3/myself
JiraAccountId: 'atlassian_user_account_id'
tempoCloudURL: 'https://api.tempo.io/core/3/'
tempoCloudApiKey: 'api_bearer_token_example'

dryRun: false
delete: false
utc: '+01:00'
# A list of issueKeys that will be compounded together instead of being a separate entry
compact:
  all: false
  specificIssueKeys:
    - 'MAGENTO-123'
