togglBaseURL: 'https://www.toggl.com/api/v8/'
togglAPIToken: ''

tempoBaseURL: 'https://example.com/rest/tempo-timesheets/3/'
tempoUserName: ''
tempoPassword: ''

dryRun: false
# A list of issueKeys that will be compounded together instead of being a separate entry
compact:
  all: false
  specificIssueKeys:
    - 'MAGENTO-123'
