togglBaseURL: 'https://www.toggl.com/api/v8/'
togglAPIToken: ''

tempoBaseURL: 'https://api.tempo.io/core/3/'
tempoUserName: ''
tempoPassword: ''
# email or ID. 
# To get ID go to your Jira profile page and extract it from URL https://yoursite.atlassian.net/jira/people/<ID>
tempoWorker: 'worker@email.com'

dryRun: false
delete: false
utc: '+01:00'
# A list of issueKeys that will be compounded together instead of being a separate entry
compact:
  all: false
  specificIssueKeys:
    - 'MAGENTO-123'
